"""
Marketing Session - Individual customer marketing campaign execution.

This module handles:
- Customer segmentation using transaction history and satisfaction metrics
- Marketing hook quality evaluation using cosine similarity with optimal hooks
- Customer visit probability updates based on marketing effectiveness
- Session history persistence for performance tracking
"""
from models.registries import ItemCatalogue
from agents.marketing_agent import MarketingAgent
from agents.opro import Opro
from agents.hooks import optimal_hooks as default_optimal_hooks, init_llm_instruction_prompts, fallback_hooks
from customers.customer_interactions import CustomerResponse
from models.registries import TransactionRegistry
from models.models import CustomerSegment
import numpy as np
from typing import Optional, Dict, List, Any, Union
from datetime import date


class MarketingSession:
    # Algorithm parameters from PDF
    AT_RISK_DAYS = 60
    AVG_VAL_L = 15
    AVG_VAL_H = 45
    
    def __init__(self, client, item_catalogue: ItemCatalogue, marketing_agent: MarketingAgent, transaction_registry: TransactionRegistry, k: int, simulation_day: int = 1, proba_update_factor: float = 1.25, optimal_hooks: Optional[Dict[str, str]] = None, current_hooks: Optional[Dict[str, str]] = None, current_hook_embeddings: Optional[Dict[str, Any]] = None, hook_evaluator: Optional[Any] = None):
        self.client = client
        self.item_catalogue = item_catalogue
        self.marketing_agent = marketing_agent
        self.transaction_registry = transaction_registry
        self.k = k
        self.simulation_day = simulation_day
        self.customer_response = CustomerResponse(client, marketing_agent.llm_service)
        self.session_history: List[Dict[str, Any]] = []
        self.proba_update_factor = proba_update_factor
        
        # Store pre-computed hook embeddings and hook evaluator for optimization
        self.current_hook_embeddings = current_hook_embeddings or {}
        self.hook_evaluator = hook_evaluator
        
        # Set optimal hooks for each segment (either provided or use defaults from PDF)
        if optimal_hooks is None:
            self.optimal_hooks = default_optimal_hooks.copy()
        else:
            self.optimal_hooks = optimal_hooks.copy()

        # Ensure we have a default hook entry
        if "Default" not in self.optimal_hooks:
            self.optimal_hooks["Default"] = "Personalized Just For You: Special Offers Inside"
        self.llm_instruction_prompt = init_llm_instruction_prompts.copy()
        self.persisted_operation_ids: List[int] = []

        # Store current hooks generated by WorldSimulator
        self.current_hooks = current_hooks or {}

    def run_session(self):
        """Run the complete marketing session."""
        # 1. Classification of customer segment
        customer_segment = self.classify_customer_segment() # CustomerSegment.HIGH_VALUE_CUSTOMERS.value
        
        # 3. Use pre-generated hook from WorldSimulator
        selected_hook = self.current_hooks.get(customer_segment)
        
        if not selected_hook:
            # Fallback to optimal hooks if current_hooks is empty
            selected_hook = self.optimal_hooks.get(customer_segment, self.optimal_hooks.get("Default", "Special offers just for you!"))

        marketing_email, client_response, hook_quality_score = self.run_step(self.session_history, selected_hook, customer_segment, self.llm_instruction_prompt.get(customer_segment))
        
        # Update visit probability
        self.update_customer_visit_proba(hook_quality_score)
        
        self.session_history.append({
            'marketing_email': marketing_email,
            'client_response': client_response,
            'customer_segment': customer_segment,
            'email_hook': selected_hook,
            'llm_hook_instruction': self.llm_instruction_prompt.get(customer_segment)
        })

        return self.session_history
    
    def run_step(self, session_history, email_hook=None, customer_segment=None, llm_hook_instruction=None):
        """Run a single step of the marketing session."""
        # Marketing agent creates MarketingEmail for client
        # Pass the email hook, segment, and LLM instruction to potentially customize the message
        marketing_email = self.marketing_agent.createMessage(self.client, email_hook, customer_segment, llm_hook_instruction)
        
        # Client creates response based on the marketing email object
        client_response = self.customer_response.create_response(marketing_email)

        # Use the hook evaluator to get the score of the hook
        hook_quality_score = 0.5  # Default score
        if hasattr(marketing_email, 'marketing_hook') and marketing_email.marketing_hook:
            hook_quality_score = self.evaluate_hook_quality(
                marketing_email.marketing_hook, 
                customer_segment if customer_segment else "Default"
            )
        
        return marketing_email, client_response, hook_quality_score

    
    def classify_customer_segment_old(self) -> str:
        """
        Classify customer segment based on Algorithm 1 from the PDF document.
        Segments:
            - N (Newcomers): No purchase history
            - A (At-risk Customers): Not N and last purchase > AT_RISK_DAYS ago
            - H (High-Value Customers): Not (N or A) and has average value ≥ AVG_VAL_H
            - L (Low-Value Customers): Not (N or A) and has average value ≤ AVG_VAL_L
            - R (Regular Customers): All others
        Parameters from PDF:
            AT_RISK_DAYS = 60
            AVG_VAL_L = 15
            AVG_VAL_H = 45
        Returns:
            str: Customer segment (N, H, R, L, A)
        """

        customer_id = self.client.cid
        
        # Get customer transactions
        transactions = self.transaction_registry.get_customer_transactions(customer_id)
        
        # Step 1: Check if customer has no purchase history (Newcomers)
        if not transactions:
            return CustomerSegment.NEWCOMERS.value
        
        # Calculate metrics for segmentation
        num_purchases = len(transactions)
        
        # Calculate days since last purchase
        last_transaction_day = self.transaction_registry.get_customer_last_transaction_day(customer_id)
        days_since_last_purchase: Union[int, float]
        if last_transaction_day:
            if isinstance(last_transaction_day, date):
                # Convert date to simulation day equivalent for calculation
                # Use a reference date (2024-10-02 = simulation day 1) to calculate relative days
                from datetime import datetime
                reference_date = datetime(2024, 10, 2).date()  # First date in transactions.tsv
                days_since_reference = (last_transaction_day - reference_date).days
                transaction_simulation_day = days_since_reference + 1  # 1-based simulation days
                days_since_last_purchase = self.simulation_day - transaction_simulation_day
            else:
                days_since_last_purchase = self.simulation_day - last_transaction_day
        else:
            days_since_last_purchase = float('inf')
        
        # # Get customer satisfaction from client data
        # satisfaction = self.client.satisfaction
        
        # Calculate Average Order Value (AOV)
        aov = self.transaction_registry.get_customer_average_order_value(customer_id)

        # Step 2: Check for At-risk Customers (A)
        if days_since_last_purchase > self.AT_RISK_DAYS:
            return CustomerSegment.AT_RISK_CUSTOMERS.value

        # Step 3: Check for High-Value Customers (H)
        if aov >= self.AVG_VAL_H:
            return CustomerSegment.HIGH_VALUE_CUSTOMERS.value

        # Step 4: Check for Low-Value Customers (L)
        if aov <= self.AVG_VAL_L:
            return CustomerSegment.LOW_VALUE_CUSTOMERS.value

        # Step 5: Default case - Regular Customers (R)
        return CustomerSegment.REGULAR_CUSTOMERS.value

    def classify_customer_segment(self) -> str:
        """
        Get the stored customer segment from the database.
        
        Returns:
            str: Customer segment value stored in database
        """
        return self.client.segment


    def generate_email_hooks(self, llm_instruction_prompt: Optional[str] = None, customer_segment: Optional[str] = None) -> List[str]:
        """
        Generate personalized email marketing hooks using the LLM instruction prompt.
        
        Args:
            llm_instruction_prompt: The OPRO-optimized prompt that instructs LLM how to generate hooks (optional)
            customer_segment: Customer segment (N, H, R, L, A) (optional)
            
        Returns:
            list: List of generated email hooks for the customer
        """
        # Use default segment if none provided
        if customer_segment is None:
            customer_segment = CustomerSegment.REGULAR_CUSTOMERS.value
        
        # If no LLM instruction prompt provided, use fallback hardcoded hooks
        if llm_instruction_prompt is None:
            return self._get_fallback_hooks(customer_segment)
        
        # Use LLM Service to generate hooks based on the instruction prompt
        try:
            # Call LLM service with the instruction prompt as-is
            llm_response = self.marketing_agent.llm_service.generate_text(llm_instruction_prompt)
            
            # Parse the response into individual hooks
            hooks = [hook.strip() for hook in llm_response.split('\n') if hook.strip()]
            
            # Ensure we have exactly 3 hooks
            if len(hooks) >= 3:
                return hooks[:3]
            elif len(hooks) > 0:
                # If we got fewer than 3, repeat the last one to get to 3
                while len(hooks) < 3:
                    hooks.append(hooks[-1])
                return hooks
            else:
                # If LLM returned no valid hooks, fallback to hardcoded
                return self._get_fallback_hooks(customer_segment)
                
        except Exception as e:
            # If LLM call fails, fallback to hardcoded hooks
            print(f"LLM call failed, using fallback hooks: {e}")
            return self._get_fallback_hooks(customer_segment)
    
    def _get_fallback_hooks(self, customer_segment: str) -> List[str]:
        """
        Get fallback hardcoded hooks when LLM is not available or fails.
        
        Args:
            customer_segment: Customer segment (H, N, A)
            
        Returns:
            list: List of fallback email hooks
        """
        if customer_segment == CustomerSegment.HIGH_VALUE_CUSTOMERS.value:
            return [
                "🌟 Exclusive VIP Preview: Your Premium Collection Awaits Inside",
                "As Our Valued VIP: First Access to Limited Edition Items",
                "Your Loyalty Deserves More: Exclusive Member-Only Deals Inside"
            ]
        elif customer_segment == CustomerSegment.NEWCOMERS.value:
            return [
                "Welcome! Your Personal Shopping Journey Starts Here 🎉",
                "New Here? Discover Why Thousands Love Shopping With Us",
                "Your Welcome Gift Is Ready - Plus Our Most Popular Picks!"
            ]
        elif customer_segment == CustomerSegment.AT_RISK_CUSTOMERS.value:
            return [
                "We Miss You! Here's What You've Been Missing + Special Return Offer",
                "Remember Us? Your Favorites Are Back & Better Than Ever",
                "Welcome Back! Exclusive Comeback Deal Just For You Inside"
            ]
        else:
            return [
                "Personalized Just For You: Special Offers Inside",
                "Don't Miss Out: Your Curated Selection Awaits",
                "Exclusive Deals Matching Your Style"
            ]

    def persist_session_history(self):
        """
        Persist email history, customer responses, and prompt performance data.
        Saves each session step as individual MarketingOperation objects.
        """
        from models.models import MarketingOperation
        from models.registries import marketing_operation_registry
        
        saved_operation_ids = []
        
        # Convert each session step to MarketingOperation and save
        for step in self.session_history:
            marketing_email = step['marketing_email']
            client_response = step['client_response']
            
            # Create MarketingOperation from the session step
            marketing_operation = MarketingOperation(
                mid=0,  # Will be assigned by registry
                cid=self.client.get('cid', 0),
                simulation_day=self.simulation_day,
                marketing_hook=marketing_email.marketing_hook,
                item_recommendations=marketing_email.recommended_item_ids,
                entire_ad_message=marketing_email.get_full_email_content(),
                website_visited=False,  # TODO: Implement website visit tracking
                client_response=str(client_response),
                llm_hook_instruction=step.get('llm_hook_instruction', '') or ''
            )
            
            # Save to database using registry
            operation_id = marketing_operation_registry.save_marketing_operation(marketing_operation)
            saved_operation_ids.append(operation_id)
        
        # Store operation IDs for reference
        self.persisted_operation_ids = saved_operation_ids
        
        return saved_operation_ids
    
    def update_customer_visit_proba_old(self, score: float) -> None:
        """
        Update the customer's visit probability based on a score (old additive method).

        Args:
            score: A value between -1.0 and 1.0 representing the impact on visit probability
        """
        if not -1.0 <= score <= 1.0:
            raise ValueError("Score must be between -1.0 and 1.0")

        current_proba = self.client.visit_probability
        new_proba = current_proba + score * self.proba_update_factor

        # Clamp the new probability between 0.0 and 1.0
        new_proba = max(0.0, min(1.0, new_proba))

        # Update the client's visit probability
        self.client.visit_probability = new_proba
        self.client.save()  # Save changes to database

    def update_customer_visit_proba(self, score: float) -> None:
        """
        Update the customer's visit probability based on a score.
        
        Args:
            score: A value between 0.0 and 1.0 representing the impact on visit probability
        """
        if not -1.0 <= score <= 1.0:
            raise ValueError("Score must be between -1.0 and 1.0")
        score = max(score, 0)
        new_proba = score * self.proba_update_factor
        
        # Clamp the new probability between 0.0 and 1.0
        new_proba = max(0.0, min(1.0, new_proba))
        
        # Update the client's visit probability
        self.client.visit_probability = new_proba
        self.client.save()  # Save changes to database
    
    def evaluate_hook_quality(self, hook: str, customer_segment: str) -> float:
        """
        Evaluate marketing hook quality using cosine similarity with optimal hooks.
        Implements: cos-sim(h, h*_s) from equation (4) in Section 4.2.1 of PDF.
        
        Uses pre-computed embeddings when available for optimization.

        Args:
            hook: The generated marketing hook text
            customer_segment: Customer segment (N, H, A, L, R)
            
        Returns:
            Hook quality score between 0.0 and 1.0
        """
        if not hook or not hook.strip():
            return 0.0  # Return 0 for empty hooks
        
        if not self.hook_evaluator:
            print("Warning: No hook evaluator available, returning default score")
            return 0.5  # Default fallback score if no evaluator available
        
        # Check if we have pre-computed embedding for this segment's hook
        if (customer_segment in self.current_hook_embeddings and
            self.current_hook_embeddings[customer_segment] is not None and
            hook == self.current_hooks.get(customer_segment)):

            try:
                # Use pre-computed embedding for optimization
                hook_embedding = self.current_hook_embeddings[customer_segment]
                return self.hook_evaluator.evaluate_hook_quality_with_embedding(
                    hook_embedding, customer_segment
                )
            except Exception as e:
                print(f"Error using pre-computed embedding, falling back to individual computation: {e}")
                # Fall through to individual computation

        # Fallback to individual computation using hook_evaluator
        try:
            return self.hook_evaluator.evaluate_hook_quality(hook, customer_segment)
        except Exception as e:
            print(f"Error evaluating hook quality: {e}")
            return 0.5  # Default fallback score

